image: mjerabek/vivado
build:
    image: mjerabek/vivado
    tags: [vivado]
    stage: build
    before_script:
        # /opt/xilinx is mounted as docker volume (set in gitlab-runner config file)
        - source /opt/xilinx/vivado-2017.4/settings.sh
    script:
        - make system_project
        - make system/system.hdf system/system.bit.bin
    artifacts:
        when: always
        paths:
            - system/system.hdf
            - system/system.bit
            - system/system.bit.bin
            - system/project
            - system/src/top
    only:
        - /^autobuild_.*/
    except:
        - web
        - schedules

fetch_ctucanfd_driver:
    stage: build
    only:
        - /^autobuild_.*/
    except:
        - web
        - schedules
    script:
        - python3 ci/fetch_ctucanfd_driver.ko $(git rev-parse @:modules/CTU_CAN_FD)
        # now we have both the driver and the bitstream
        - ansible-playbook ci/test_can.yml

pull-submodules:
    tags: [vivado]
    stage: build
    only:
        - schedules # on ${MASTER_BRANCH}
        - web # for debugging
    before_script:
        # Deploy key: public part specified in project deploy keys
        #             private part in docker volume, mounted on /depkey
        # Add the private key to this user
        - eval $(ssh-agent -s) && ssh-add /depkey/id_rsa
        - mkdir ~/.ssh && cp /depkey/config ~/.ssh/config
        # Docker specific settings
        - git config --global user.name "Gitlab CI"
        - git config --global user.email "bot@gitlabci"
    script:
        - git checkout ${AUTO_BRANCH} && git merge origin/${AUTO_BRANCH} --ff-only
        - "git remote set-url --push origin $(echo ${CI_REPOSITORY_URL} | sed -re 's~^[^@]+@([^/]+)~git@\\1:~')"
        - git merge origin/${MASTER_BRANCH}
        - git submodule update --remote --merge modules/CTU_CAN_FD modules/sja1000
        - (cd modules/zlogan && git pull origin zlogan-component)
        - "git commit -q -m 'auto: modules update' -a || true"
        - git push || true
variables:
    GIT_SUBMODULE_STRATEGY: recursive
    MASTER_BRANCH: microzed_apo_canfd_test
    AUTO_BRANCH: autobuild_microzed_apo_canfd_test
